### ISSUE TITLE
unsafe code

### ISSUE THREAD

**Issue by wineggdrop** [zcgonvh/DCOMPotato#1]
Is it possible to make the code as safe code?

**Comment by zcgonvh** [comment]
yes, you can use [Marshal](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal) instead of unsafe pointer or memory allocation like this(mcppotato):

```c#
MULTI_QI[] qis = new MULTI_QI[1];
qis[0] = new MULTI_QI();
IntPtr pIID_IUnk=Marshal.AllocHGlobal(16);
Marshal.Copy(new Guid("{00000000-0000-0000-C000-000000000046}").ToByteArray(),0,pIID_IUnk,16);
qis[0].pIID = pIID_IUnk;
qis[0].pItf = IntPtr.Zero;
qis[0].hr = 0;
var pobj = Marshal.GetComInterfaceForObject(wrapper, typeof(IStorage));
IntPtr vtbl = Marshal.ReadIntPtr(pobj);
Marshal.WriteIntPtr(vtbl + 8 * 0x2,Marshal.GetFunctionPointerForDelegate(new Action(ManagedIStorageWrapper.test)));
var ret = NativeMethods.CoGetInstanceFromIStorage(IntPtr.Zero, ref CLSID_McpManagementService, IntPtr.Zero, 4, pobj, 1, qis);
Marshal.Release(pIID_IUnk);//may leak!
```

obviously, `verifiably safe code` is inflexible, unsafe code allows us to write a native-c-style code in csharp and helps us to control vtbl layout more precisely. The CLR not provide any way to create a native-IUnknown object, `AddRef` and `Release` is always managed by RCW. So we have to create a fake vtbl manually, using the helper methods as an alternative to unsafe code is self-defeating IMHO.

> Unsafe code in C# isn't necessarily dangerous

from [MSDN](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code)

**Comment by wineggdrop** [comment]
since I am not familiar with C#,I will try my best.thx for the help anyway




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zcgonvh/DCOMPotato"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 凌晨3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zcgonvh/DCOMPotato] unsafe code (Issue #1)





 
yes, you can use Marshal instead of unsafe pointer or memory allocation like this(mcppotato):
 MULTI_QI[] qis = new MULTI_QI[1]; qis[0] = new MULTI_QI(); IntPtr pIID_IUnk=Marshal.AllocHGlobal(16); Marshal.Copy(new Guid("{00000000-0000-0000-C000-000000000046}").ToByteArray(),0,pIID_IUnk,16); qis[0].pIID = pIID_IUnk; qis[0].pItf = IntPtr.Zero; qis[0].hr = 0; var pobj = Marshal.GetComInterfaceForObject(wrapper, typeof(IStorage)); IntPtr vtbl = Marshal.ReadIntPtr(pobj); Marshal.WriteIntPtr(vtbl + 8 * 0x2,Marshal.GetFunctionPointerForDelegate(new Action(ManagedIStorageWrapper.test))); var ret = NativeMethods.CoGetInstanceFromIStorage(IntPtr.Zero, ref CLSID_McpManagementService, IntPtr.Zero, 4, pobj, 1, qis); Marshal.Release(pIID_IUnk);//may leak!
 
obviously, verifiably safe code is inflexible, unsafe code allows us to write a native-c-style code in csharp and helps us to control vtbl layout more precisely. The CLR not provide any way to create a native-IUnknown object, AddRef and Release is always managed by RCW. So we have to create a fake vtbl manually, using the helper methods as an alternative to unsafe code is self-defeating IMHO.
  
Unsafe code in C# isn't necessarily dangerous
  
from MSDN
